[package]
name = "MultiUp_Direct_2_5_1"
version = "2.5.1"
authors = ["Redpoint"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = "fat"
#debug = true


[dependencies]
async-recursion = { version = "1.0.4" }
crossbeam-channel = { version = "0.5.8" }
eframe = { version = "0.22.0" }
egui_extras = { version = "0.22.0" }
futures = { version = "0.3.28" }
reqwest = { version = "0.11.18", features = ["json", ] }
regex = { version = "1.8.4" }
scraper = { version = "0.16.0" }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = { version = "1.0.96" }
tokio = { version = "1.28.2", features = ["full"] }
tokio-util = { version = "0.7.7" }
webbrowser = { version = "0.8.9" }


[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false