[package]
name = "MultiUp_Direct_v1_3_0"
version = "1.3.0"
authors = ["Redpoint"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[profile.release]
#debug = true


[dependencies]
crossbeam-channel = "0.5.8"
eframe = { version = "0.21.3" }
once_cell = "1.17.1"
reqwest = { version = "0.11.16", features = ["json", "multipart", "stream"] }
regex = "1.8.1"
scraper = "0.16.0"
serde = { version = "1.0.160", features = ["derive"]}
serde_json = "1.0.96"
tokio = { version = "1.27.0", features = ["full"] }
tokio-util = "0.7.7"
webbrowser = "0.8.9"


[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false